"""Initiales Datenmodell

Revision ID: 6f1fab9af783
Revises: 
Create Date: 2026-10-09 11:10:15.515583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1fab9af783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('budget_chf', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('hours_available', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('budget_chf >= 0', name=op.f('ck_household_budget_positive')),
    sa.CheckConstraint('hours_available >= 0', name=op.f('ck_household_hours_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_household'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('token_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('criterion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.CheckConstraint("direction IN ('benefit', 'cost')", name=op.f('ck_criterion_direction_valid')),
    sa.CheckConstraint('weight BETWEEN 1 AND 5', name=op.f('ck_criterion_weight_range')),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_criterion_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_criterion')),
    sa.UniqueConstraint('household_id', 'name', name='uq_criterion_household_name')
    )
    with op.batch_alter_table('criterion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criterion_household_id'), ['household_id'], unique=False)

    op.create_table('membership',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name=op.f('ck_membership_role_valid')),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_membership_household_id_household'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_membership_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'household_id', name=op.f('pk_membership'))
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_hours', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('idee','bewertet','geplant','in_arbeit','erledigt','verworfen')", name=op.f('ck_project_status_valid')),
    sa.CheckConstraint('estimated_cost >= 0', name=op.f('ck_project_est_cost_positive')),
    sa.CheckConstraint('estimated_hours >= 0', name=op.f('ck_project_est_hours_positive')),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_project_created_by_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], name=op.f('fk_project_household_id_household'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_status'), ['status'], unique=False)

    op.create_table('project_dependency',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['project.id'], name=op.f('fk_project_dependency_depends_on_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_dependency_project_id_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'depends_on_id', name=op.f('pk_project_dependency'))
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('criterion_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value BETWEEN 1 AND 5', name=op.f('ck_rating_value_range')),
    sa.ForeignKeyConstraint(['criterion_id'], ['criterion.id'], name=op.f('fk_rating_criterion_id_criterion'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_rating_project_id_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_rating_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rating')),
    sa.UniqueConstraint('project_id', 'user_id', 'criterion_id', name='uq_rating_once')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_criterion_id'), ['criterion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_user_id'))
        batch_op.drop_index(batch_op.f('ix_rating_project_id'))
        batch_op.drop_index(batch_op.f('ix_rating_criterion_id'))

    op.drop_table('rating')
    op.drop_table('project_dependency')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_status'))
        batch_op.drop_index(batch_op.f('ix_project_household_id'))

    op.drop_table('project')
    op.drop_table('membership')
    with op.batch_alter_table('criterion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criterion_household_id'))

    op.drop_table('criterion')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_token'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('household')
    # ### end Alembic commands ###
